### ISSUE TITLE
minor changes

### ISSUE THREAD

**Issue by jain-shobhit** [jain-shobhit/SteadyStateTool#1]
@gergelybuza Thanks for these changes. 
1. Can you please make a separate directory inside vonKarman which contains the FECode files. Ideally, there should remain only two main script files for straight and curved beam which reproduce the figures 5/6 and 8 from the manuscript, respectively. The mode selection algorithm should be called from within these scripts.
2. Please also combine the motiv_example and plotter files to result in one script that simply produces Figure 3 of the manuscript. 
3. It seems that you have included 3 new functions in the SSR class, SSM2, SSMcomps and FRC. However, there are a lot more function headers in the class file. Please remove any redundant function headers,
![image](https://user-images.githubusercontent.com/22640963/92422827-08dc0900-f17f-11ea-9e10-6cfb716abc62.png)

**Comment by gergelybuza** [comment]
@jain-shobhit Important before you submit: On the other repo, I changed the manuscript, as the W matrices in the motivating example were never updated to match the new parameters.

As for point 1. here: I've had to add an optional parameter to mode selection that allows the user to specify an initial selection. (This is a useful feature anyway.) Originally, both examples were done this way, but since the curvedbeam example gives the same recommendation if I let it repeat and not specify an initial set, I left it that way.
